### ISSUE TITLE
Does not show secondary sections (reveal v.4)

### ISSUE THREAD

**Issue by a-i-m-a-r** [e-gor/Reveal.js-TOC-Progress#18] opened 2021-03-11 15:04 UTC
I am using reveal v4 and the plugin is not showing secondary sections. It works in v3.
Is there an easy way to fix it for v4?
Thank you.

**Comment by e-gor** [comment] 2021-03-14 18:27
Duplicate of #16, solution there. Closing.

**Closed by e-gor** 2021-03-14 18:27 UTC
